# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 363)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 100, 111, 71))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 18))
        self.menubar.setObjectName("menubar")
        self.menusss = QtWidgets.QMenu(self.menubar)
        self.menusss.setObjectName("menusss")
        self.menusss_2 = QtWidgets.QMenu(self.menubar)
        self.menusss_2.setObjectName("menusss_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action1_1 = QtWidgets.QAction(MainWindow)
        self.action1_1.setObjectName("action1_1")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2_1 = QtWidgets.QAction(MainWindow)
        self.action2_1.setObjectName("action2_1")
        self.menusss.addAction(self.action1_1)
        self.menusss.addAction(self.action1_2)
        self.menusss_2.addAction(self.action2_1)
        self.menubar.addAction(self.menusss.menuAction())
        self.menubar.addAction(self.menusss_2.menuAction())
        self.toolBar.addAction(self.action1_1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menusss.setTitle(_translate("MainWindow", "1"))
        self.menusss_2.setTitle(_translate("MainWindow", "2"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action1_1.setText(_translate("MainWindow", "1.1"))
        self.action1_2.setText(_translate("MainWindow", "1.2"))
        self.action2_1.setText(_translate("MainWindow", "2.1"))
